#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Prepares system state for GitDeploy.
"""

import sys
import io
import argparse
import logging
import ConfigParser
import subprocess
import shutil

from git_deploy.config import configure, log, set_log, GitDeployConfigError
from git_deploy.utils import scp_file


INI_FILE = 'scripts/git-deploy.ini'

HOSTTYPE_CLIENT = 'client'
HOSTTYPE_TARGET = 'target'

log_format = "%(asctime)s %(levelname)-8s %(message)s"
handler = logging.StreamHandler(sys.stderr)
handler.setFormatter(logging.Formatter(fmt=log_format,
                     datefmt='%b-%d %H:%M:%S'))

def parseargs():
    """Parse command line arguments.

    Returns *args*, the list of arguments left over after processing.

    """
    parser = argparse.ArgumentParser(
        description="This script serves as the entry point for git deploy.",
        epilog="",
        conflict_handler="resolve",
        usage="git-deploy method [remote] [branch]"
              "\n\t[-q --quiet] \n\t[-s --silent] "
              "\n\t[-v --verbose] \n\t[-c --count [0-9]+] \n\t[-f --force] "
              "\n\t[-t --tag] \n\t[-a --auto_sync] "
              "\n\t[-y --sync SCRIPT NAME] "
              "\n\nmethod=[start|sync|abort|revert|diff|show_tag|"
              "log_deploys|finish]"
    )

    parser.allow_interspersed_args = False

    defaults = {
        "quiet": 0,
        "silent": False,
        "verbose": 0,
    }

    # Global options.
    parser.add_argument("-t", "--hosttype",
                        default=HOSTTYPE_TARGET, type=str,
                        help="Specify the init type - is this a client or "
                             "target host?")
    parser.add_argument("-q", "--quiet",
                        default=defaults["quiet"], action="count",
                        help="decrease the logging verbosity")
    parser.add_argument("-s", "--silent",
                        default=defaults["silent"], action="store_true",
                        help="silence the logger")
    parser.add_argument("-v", "--verbose",
                        default=defaults["verbose"], action="count",
                        help="increase the logging verbosity")

    return parser.parse_args()


def git_config_global_set(section, prop, value):
    proc = subprocess.Popen("git config --global {0}.{1} {2}".format(
        section, prop, value
    ).split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    proc.communicate()


def main():

    args = parseargs()
    set_log(args, sys.stdout, sys.stderr)

    # Extract the init type
    if args.hosttype != HOSTTYPE_CLIENT and args.hosttype != HOSTTYPE_TARGET:
        # default to client on bas input
        hosttype = HOSTTYPE_CLIENT
    else:
        hosttype = args.hosttype

    # Process INI
    try:
        with file(INI_FILE, 'r') as f:
            config_handle = f.read()
        config = ConfigParser.RawConfigParser(allow_no_value=True)
        config.readfp(io.BytesIO(config_handle))
    except IOError:
        logging.error(__name__ + ' :: Could not find .ini.')
        return

    # Set the ini conf
    for section in config.sections():
        for name, value in config.items(section):
            # git config
            if section == 'deploy':
                log.info("{0} :: Setting config for {1}.{2} @ {3}".format(
                    __name__, section, name, value))
                git_config_global_set(section, name, value)

            # cp git-deploy
            if section == 'system' and name == 'run_root':
                log.info("{0} :: Adding git-deploy exec to '{1}'".format(
                    __name__, value
                ))
                shutil.copy('scripts/git-deploy', value)

    try:
        log.info("{0} :: loading config ...".format(__name__))
        _config = configure()
    except GitDeployConfigError as e:
        log.error("{0} :: call to configure() failed - '{1}'".format(
            __name__, e.message))
        sys.exit(e.exit_code)

    # Process different host type initialization
    if hosttype == HOSTTYPE_CLIENT:
        hook_dir = "{0}/{1}".format(_config['client_path'], _config['hook_dir'])
        git_deploy_push_script = 'git-deploy/default-hooks/default-client-push.py'

        log.info("{0} :: Copying '{1}' to '{2}'".format(
            __name__, git_deploy_push_script, hook_dir))

        shutil.copy('git_deploy/default-hooks/default-client-push.py',
                    hook_dir)

    elif hosttype == HOSTTYPE_TARGET:
        remote_hook_dir = "{0}/{1}".format(_config['path'], _config['hook_dir'])
        git_deploy_pull_script = 'git_deploy/default-hooks/default-target-pull.py'

        log.info("{0} :: secure copying '{1}' to '{2}'".format(
            __name__, git_deploy_pull_script, remote_hook_dir))

        scp_file(_config['target'],
                 git_deploy_pull_script,
                 remote_hook_dir,
                 _config['user.name'],
                 _config['deploy.key_path']
        )


def cli():
    sys.exit(main())

if __name__ == "__main__":  # pragma: nocover
    cli()
